apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: w010rebjw-go-gitops
  description: This is GitOps manifest for w010rebjw-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=w010rebjw-go
    backstage.io/kubernetes-id: w010rebjw-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: w010rebjw-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:w010rebjw-go
